stages:
  - test

cypress_tests:
  image: cypress/base:14
  stage: test
  script:
    - npm install
    - $(npm bin)/cypress run --headless --browser chrome
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots